# This is a basic workflow to help you get started with Actions

name: Hellhades

on:
  schedule:
    - cron:  '0 12 * * *'
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update list
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        make CREATOR=hellhades update_youtube
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "feat: updated hellhades"
        author: Geoffrey Bauduin <geoffreybauduin@users.noreply.github.com>

        title: 'Updated hellhades'
        base: master
        body: |
          Automatically generated
        assignees: geoffreybauduin
        reviewers: geoffreybauduin
